apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.applicationName }}-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    {{- with .Values.labels }}
    matchLabels:
    {{- toYaml . | nindent 8 }}
    {{- end }} 