{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.applicationName }}-secret
data:
  {{ .Values.secretStringName }}: {{ .Values.secretContent | toYaml | nindent 2 }}
{{- end }}